### ISSUE TITLE
I cant open the script

### ISSUE THREAD

**Issue by korre21aek** [kochlisGit/ProphitBet-Soccer-Bets-Predictor#18]
I cant open the script, i have send u a email aswell. I get a error 
![Skärmbild 2023-04-05 205133](https://user-images.githubusercontent.com/129910949/230177149-18b524b6-0ba3-4933-b6ac-d01718e714e1.png)

**Comment by kochlisGit** [comment]
Yes, it appears that imblearn is not installed. You need to install it: pip install imbalanced-learn Στις 5 Απρ 2023 21:51, ο χρήστης korre21aek ***@***.***> έγραψε:
I cant open the script, i have send u a email aswell. I get a error

**Comment by korre21aek** [comment]
Alright, Do you use a Virtual Machine?

**Comment by kochlisGit** [comment]
It can run on virtual machine, but not.

**Comment by korre21aek** [comment]
![issue 3](https://user-images.githubusercontent.com/129910949/230375122-59959df2-eb6a-4a5e-821d-355bd2d5289f.png)
Now i have anew issue. Even if i have installed  Tensorflow 2.9.1 i still get the same issue. I realised u are greek is it ok if we take it in greek or no?

**Comment by kochlisGit** [comment]
You need to go to documentation on GitHub page and install the required libraries!
Best Regards

**Comment by korre21aek** [comment]
yeah i did it aswell, now when i run python main.py im getting everything black on cmd. i will post a picture aswell. Thanks for the help i appreciate it alot. 
![issue 4](https://user-images.githubusercontent.com/129910949/230377915-293138d3-a1c3-47ad-b115-a3f7d2188271.png)

**Comment by korre21aek** [comment]
I found out a way how to make it work. Sadly i got other issues but i will make a new issue for that. Thanks for the help everyone!
