### ISSUE TITLE
imblearn is missing?

### ISSUE THREAD

**Issue by Janimarton** [kochlisGit/ProphitBet-Soccer-Bets-Predictor#32]
Hello!

I installed the necessary dependencies, but when I want to run the program by double-clicking on main.py, nothing happens. When started from CMD, it throws this error:
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from database.repositories.model import ModelRepository
  File "...\ProphitBet-Soccer-Bets-Predictor-main\database\repositories\model.py", line 3, in <module>       
    from models.model import Model
  File "...\ProphitBet-Soccer-Bets-Predictor-main\models\model.py", line 3, in <module>
    from imblearn.over_sampling import SVMSMOTE
ModuleNotFoundError: No module named 'imblearn'

How could I avoid this issue?

**Comment by kochlisGit** [comment]
Did you install imbalanced-learn?
`pip install imbalanced-learn`

There is another library called "imblearn", which is different than the one used in this project.  Perhaps you installed that one instead of imbalanced-learn as described in the documentation.

**Comment by AFN7** [comment]
Also, you can check whether you installed it or not by typing: `pip show imblearn` or `pip show imbalanced-learn`.

You can create .bat file and make shortcut to it and start it with one click.

```
@echo off
python "C:\FOLDER\main.py"
pause
```

**Comment by Janimarton** [comment]
Thank you!
Yes, I did not install `imbalanced-learn`.
I just installed the packages from `requirements.txt`.
Now it's working fine.
