### ISSUE TITLE
Import fixtures and odds not accurate 

### ISSUE THREAD

**Issue by KnightRider37** [kochlisGit/ProphitBet-Soccer-Bets-Predictor#43]
When importing fixtures from footy stats html, the import is all wrong and have to change teams and odds. Anyway to fix this ? Thanks

**Comment by ZockerFox** [comment]
Hi, that correct.  The odds at footystats are not very accurate. In my app i added a import of the odds and fixtures from betmonitor.com. That works well.

**Comment by KnightRider37** [comment]
Hi, did you only change the link in the csv file or did you also change some code ? Thanks

**Comment by KnightRider37** [comment]
> Hi, that correct. The odds at footystats are not very accurate. In my app i added a import of the odds and fixtures from betmonitor.com. That works well.

Hi, did you only change the link in the csv file or did you also change some code ? Thanks

**Comment by KnightRider37** [comment]
> Hi, that correct. The odds at footystats are not very accurate. In my app i added a import of the odds and fixtures from betmonitor.com. That works well.

How did you do it? thanks

**Comment by KnightRider37** [comment]
Managed to work it out.
