### ISSUE TITLE
Fixture Prediction - Export Prediction not working

### ISSUE THREAD

**Issue by keith0811** [kochlisGit/ProphitBet-Soccer-Bets-Predictor#49]
I can import the fixtures and see the predictions listing. However, when i click on the "Export Predictions" button, the csv file when i open is blank with 0 bytes.

**Comment by KnightRider37** [comment]
Open command line again (cmd) and type: pip install pandas==1.4.3
This should install previous version of pandas library and should be fine.

**Comment by keith0811** [comment]
It works with the new pandas. Thanks.
