### ISSUE TITLE
U/O 2.5 prediction not shown

### ISSUE THREAD

**Issue by keith0811** [kochlisGit/ProphitBet-Soccer-Bets-Predictor#57]
Couldnt see the U/O 2.5 prediction selection.
https://prnt.sc/SmdjhSeIcdaz

**Comment by kochlisGit** [comment]
Yes, that's because You did not train any model for U/O 2.5. You should go to training again, and selecct "Over" instead of result.

**Comment by keith0811** [comment]
Thanks, now ok,
One more issue. Evaluation menu not seeing any matches.
https://prnt.sc/JXtjhym9BQLa

**Comment by keith0811** [comment]
Fixed the issue. Due to numpy version.
