### ISSUE TITLE
Cannot add custom league

### ISSUE THREAD

**Issue by TYRANTHOSAURUS** [kochlisGit/ProphitBet-Soccer-Bets-Predictor#8]
Tryng to add this:

England,Championship,https://www.football-data.co.uk/mmz4281/{}/E1.csv,2012,extra,https://footystats.org/england/championship/fixtures

I dont see whats wrong with it? Could you help out thnx!

**Comment by kochlisGit** [comment]
I don’t see any wrong with that. You should add this to available_leagues.csv file, which is located in database/storage/leagues/available_leagues.csv. Check this file out:
https://github.com/kochlisGit/ProphitBet-Soccer-Bets-Predictor/blob/main/database/storage/leagues/available_leagues.csv

From: ***@***.***>
Sent: Monday, February 6, 2023 5:36 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [kochlisGit/ProphitBet-Soccer-Bets-Predictor] Cannot add custom league (Issue #8)


Tryng to add this:

England,Championship,https://www.football-data.co.uk/mmz4281/{}/E1.csv,2012,extra,https://footystats.org/england/championship/fixtures<https://www.football-data.co.uk/mmz4281/%7B%7D/E1.csv,2012,extra,https:/footystats.org/england/championship/fixtures>

I dont see whats wrong with it? Could you help out thnx!

**Comment by TYRANTHOSAURUS** [comment]
Hi, thanks for the quick response. This is my database/storage/leagues/available_leagues.csv (see last line).

if i load it in app it says http 404.

`country,name,url,year_start,league_type,fixtures_url
Belgium,Jupiler-League,https://www.football-data.co.uk/mmz4281/{}/B1.csv,2012,main,https://footystats.org/belgium/pro-league/fixtures
Brazil,Serie-A,https://www.football-data.co.uk/new/BRA.csv,2012,extra,https://footystats.org/brazil/serie-a/fixtures
England,Premier-League,https://www.football-data.co.uk/mmz4281/{}/E0.csv,2012,main,https://footystats.org/england/premier-league/fixtures
France,Le-Championnat,https://www.football-data.co.uk/mmz4281/{}/F1.csv,2012,main,https://footystats.org/france/ligue-1/fixtures
Germany,Bundesliga-1,https://www.football-data.co.uk/mmz4281/{}/D1.csv,2012,main,https://footystats.org/germany/bundesliga/fixtures
Greece,Super-League,https://www.football-data.co.uk/mmz4281/{}/G1.csv,2012,main,https://footystats.org/greece/super-league/fixtures
Italy,Serie-A,https://www.football-data.co.uk/mmz4281/{}/I1.csv,2012,main,https://footystats.org/italy/serie-a/fixtures
Netherlands,Eredivisie,https://www.football-data.co.uk/mmz4281/{}/N1.csv,2012,main,https://footystats.org/netherlands/eredivisie/fixtures
Portugal,Liga-I,https://www.football-data.co.uk/mmz4281/{}/P1.csv,2012,main,https://footystats.org/portugal/liga-nos/fixtures
Scotland,Premiership,https://www.football-data.co.uk/mmz4281/{}/SC0.csv,2012,main,https://footystats.org/scotland/premiership/fixtures
Spain,La-Liga,https://www.football-data.co.uk/mmz4281/{}/SP1.csv,2012,main,https://footystats.org/spain/la-liga/fixtures
Sweden,Allsvenskan,https://www.football-data.co.uk/new/SWE.csv,2012,extra,https://footystats.org/sweden/allsvenskan/fixtures
Turkey,Futbol-Ligi-1,https://www.football-data.co.uk/mmz4281/{}/T1.csv,2012,main,https://footystats.org/turkey/super-lig/fixtures
England,Championship,https://www.football-data.co.uk/mmz4281/{}/E1.csv,2012,extra,https://footystats.org/england/championship/fixtures`

**Comment by kochlisGit** [comment]
Can you provide me with a screenshot?

**Comment by TYRANTHOSAURUS** [comment]
![prohphitbet_debug](https://user-images.githubusercontent.com/120685196/217116027-668ae7a8-7731-4548-898c-1e42b08a5898.png)

**Comment by TYRANTHOSAURUS** [comment]
![prophitbet_debug2](https://user-images.githubusercontent.com/120685196/217116121-c87a69f9-b878-4a56-a74d-943b50c5ca8a.png)

**Comment by kochlisGit** [comment]
This is a “main” league not “extra”. That’s probably why. Second divisions are also classified as “main” leagues by football-data database.

**Comment by TYRANTHOSAURUS** [comment]
I can confirm that its working, sorry thought every extra was extra!

Thanks for reply!
