### ISSUE TITLE
Accuracy of the models

### ISSUE THREAD

**Issue by rodrigom03** [kochlisGit/ProphitBet-Soccer-Bets-Predictor#84]
I have been experimenting the app and making some models with training data. 

However, no matter what settings I change or what model I use, **I can’t get an accuracy (or other metric) greater than 0.55.** 

I used every model available and change a the settings to optimize the algorithm but the highest accuracy I got was 0.55!

**Has someone got a higher accuracy on training data?**

**Comment by ByLennox** [comment]
Hey, have you found a way to increase accuracy? If so what did you do?
